export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_MOVIE_PAGE = "GET_LIST_MOVIE_PAGE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";


export const GET_LIST_CINEMA= "GET_LIST_CINEMA";
export const GET_LIST_THEATER= "GET_LIST_THEATER";
export const GET_INFO_MOVIE_THEATER = "GET_INFO_MOVIE_THEATER";